import { ReactNode, FC, memo } from "react";
import Head from "next/head";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";

type Props = {
  children: ReactNode;
};

export const Layout: FC<Props> = memo(({ children }) => {
  return (
    <>
      <Head>
        <title>TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>
          <Header />
        </header>
        <main> {children} </main>
        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
});
