import { ReactNode, FC, memo } from "react";
import Head from "next/head";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";

type Props = {
  children: ReactNode;
};

export const Layout: FC<Props> = memo(({ children }) => {
  return (
    <>
      <Head>
        <title>TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen relative">
        <Header />
        <div className="flex flex-1 relative">
          <main> {children} </main>
        </div>
        <div className="relative bottom-0 left-0">
          <Footer />
        </div>
      </div>
    </>
  );
});
